### PR TITLE
Switch to using the standardised resin-lint module for linting.

### PR DESCRIPTION
**Pull request by Page-**

### CODE REVIEW

**Comment by lekkas** [comment]
https://github.com/resin-io-modules/resin-register-device/blob/master/.hound.yml#L2 needs to be  set to `enabled: false` for the failing tests - but then we don't really need HoundCI integration for this repo at all, do we? Especially considering that HoundCI doesn't support coffeescope

**Comment by jviotti** [comment]
Yeah, let's remove `.hound.yml`, and I'll turn off this repo on hounci.com.

**Comment by Page-** [comment]
I've removed `.hound.yml`

**Comment by Page-** [comment]
I've also set up jenkins, so that we still get the linting run

**Comment by jviotti** [comment]
Awesome, feel free to merge when you're ready.

**Pull request merged**
